"""initial

Revision ID: 2575affc955b
Revises: 
Create Date: 2018-11-09 13:22:38.620125

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2575affc955b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('role_name_idx', 'role', ['name'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sid')
    )
    op.create_index('source_name_idx', 'source', ['name'], unique=False)
    op.create_index('source_sid_idx', 'source', ['sid'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('user_email_idx', 'user', ['email'], unique=False)
    op.create_index('user_username_idx', 'user', ['username'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('added_at', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('times_edited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('document_title_text_unique_idx', 'document', ['title', 'text'], unique=True)
    op.create_table('user_role_info',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.create_index('user_role_info_role_id_idx', 'user_role_info', ['role_id'], unique=False)
    op.create_index('user_role_info_user_id_idx', 'user_role_info', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_role_info_user_id_idx', table_name='user_role_info')
    op.drop_index('user_role_info_role_id_idx', table_name='user_role_info')
    op.drop_table('user_role_info')
    op.drop_index('document_title_text_unique_idx', table_name='document')
    op.drop_table('document')
    op.drop_index('user_username_idx', table_name='user')
    op.drop_index('user_email_idx', table_name='user')
    op.drop_table('user')
    op.drop_index('source_sid_idx', table_name='source')
    op.drop_index('source_name_idx', table_name='source')
    op.drop_table('source')
    op.drop_index('role_name_idx', table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
